#!/usr/bin/env node

// --------------------------------------------------------------------------------------------
// gvm: playing with C++ templates + contract tables
// --------------------------------------------------------------------------------------------

require('DoHTestLib');

// --------------------------------------------------------------------------------------------
// Compile
// --------------------------------------------------------------------------------------------

const childProcess = require('child_process');

// compile your contract
childProcess.execSync('cdt-cpp gvm.cpp --abigen --no-missing-ricardian-clause');

// --------------------------------------------------------------------------------------------
// Init
// --------------------------------------------------------------------------------------------

// args don't matter; just don't change them
fixtureInit("foobar", "hg3", "tc3");

// create the account for your contract
cleos('system newaccount eosio gvm EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV --stake-cpu "10000.0000 EOS" --stake-net "10000.0000 EOS" --buy-ram-kbytes 10000 --transfer');

// set the contract
cleos('set contract gvm . -p gvm');

// get an object to interact with it
gvm = getProxyForContract(`gvm`);

// --------------------------------------------------------------------------------------------
// Test
// --------------------------------------------------------------------------------------------

/*

gvm._logon();

// Table #0: users
gvm.createuser("usera", 10000);
gvm.createuser("userb", 20000);
gvm.createuser("userc", 30000);
gvm.createuser("userd", 40000);
gvm.createuser("usere", 50000);

// Table #1: transactions
gvm.maketrans("usera", "userb", 100);
gvm.maketrans("usera", "userc", 200);
gvm.maketrans("usera", "userd", 300);
gvm.maketrans("usera", "usere", 400);

gvm._logoff();

// Must print 5
console.log( "\n*** Table 0 count (should be 5):\n" + gvm.testrowcount(0) + "\n" );

// Must print 4
console.log( "*** Table 1 count (should be 4):\n" + gvm.testrowcount(1) + "\n" );

console.log( "Table 0:\n" + JSON.stringify( gvm.users().rows, null, 2) );
console.log( "Table 1:\n" + JSON.stringify( gvm.transactions().rows, null, 2) );

*/

// test variants

console.log("test variants");

gvm._log().testvar();

console.log("test variants done");


// --------------------------------------------------------------------------------------------
// Done
// --------------------------------------------------------------------------------------------

// just call this at the end
fixtureFinish();
