#!/usr/bin/env node

// --------------------------------------------------------------------------------------------
// gvm: playing with C++ templates + contract tables
// --------------------------------------------------------------------------------------------

require('DoHTestLib');

// --------------------------------------------------------------------------------------------
// Compile
// --------------------------------------------------------------------------------------------

const childProcess = require('child_process');

// compile your contract
childProcess.execSync('cdt-cpp gvm.cpp --abigen --no-missing-ricardian-clause');

// --------------------------------------------------------------------------------------------
// Init
// --------------------------------------------------------------------------------------------

// args don't matter; just don't change them
fixtureInit("foobar", "hg3", "tc3");

// create the account for your contract
cleos('system newaccount eosio gvm EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV --stake-cpu "10000.0000 EOS" --stake-net "10000.0000 EOS" --buy-ram-kbytes 10000 --transfer');

// set the contract
cleos('set contract gvm . -p gvm');

// get an object to interact with it
gvm = getProxyForContract(`gvm`);

// --------------------------------------------------------------------------------------------
// Test
// --------------------------------------------------------------------------------------------

// Table #0: users
gvm.createuser("usera", 50000);
gvm.createuser("userb", 9000);
gvm.createuser("userc", 88800);
gvm.createuser("userd", 70000);
gvm.createuser("usere", 60000);

// Table #1: transactions
gvm.maketrans("usera", "userb", 250);
gvm.maketrans("userc", "userd", 150);
gvm.maketrans("usere", "usera", 350);
gvm.maketrans("userc", "userd", 450);

// Must print 5
console.log( "Table 0 count (should be 5):\n" + gvm.testrowcount(0) );

// Must print 4
console.log( "Table 1 count (should be 4):\n" + gvm.testrowcount(1) );

console.log( "Table 0:\n" + JSON.stringify( gvm.users() ) );
console.log( "Table 1:\n" + JSON.stringify( gvm.transactions() ) );

// --------------------------------------------------------------------------------------------
// Done
// --------------------------------------------------------------------------------------------

// just call this at the end
fixtureFinish();
