#!/usr/bin/env node

// --------------------------------------------------------------------------------------------
// meta-test
// --------------------------------------------------------------------------------------------
// Test various functions of the metagame contract.
//
// This test is an example of a cth/DoH test that contains multiple "fixture tests", which are
//   a collection of actual test routines performed by this cth/DoH testcase file/directory.
//
// The idea is that there's a single table, bench, or "fixture" where you place a routine to
//   be tested, and when you are done with that, you remove that routine, optionally perform a
//   fixtureCleanup.js routine, and then place the next routine to be tested in the fixture.
//   We'll be calling those test routines "fixture tests" to disambiguate from "tests", which
//   are the "run" files (this file) and the directory they are in, which is the test's
//   directory (which names the top-level cth/DoH testcase to the harness).
//
// After all the fixture tests are run, if everything went well, then fixtureFinish() will
//   call fixturePrintSummary() internally to present a tally of how many fixture tests
//   passed and how many failed. If anything fails anywhere, the whole testcase fails.
//
// NOTE:
//
// fixtureRun() uses vm.runInThisContext(), which has no access to let/const variables
//   declared outside of the script to be run, so we need to use global variables to access
//   these from the fixture tests.
// As a rule of thumb, any variable that's going to be accessed by more than one test file
//   is going to be a global variable (including all of DoHTestLib's exported functions
//   and variables). This should not be a problem unless people are trying to create
//   test functions/variables that are named e.g. "init", "cleos", "CONTRACT", etc.
//   (I guess we could create a global object named 'test' and put everything into *that*,
//    but i'd rather use the shorter names for writing tests and instead be creative when
//    naming test variables/functions...)
// --------------------------------------------------------------------------------------------

// This is the recommended way to pull in the entire test library.
// Everything is dumped in the global object.
require('DoHTestLib');

// --------------------------------------------------------------------------------------------
// Init
// --------------------------------------------------------------------------------------------

fixtureInit("dohplayer1", "hg3", "tc3");

// after fixtureInit, global variable "doh" is a JS object with all DoH game constants.
console.log("Value of DoH constant 'GAME_CONTRACT' = " + doh.GAME_CONTRACT);

createBasicGame();
createBasicPlayers();
createBasicEconomy();

tokens = getProxyForContract(`tokens.${tcn_target}`);
meta = getProxyForContract(`meta.${doh_target}`);
clock = getProxyForContract(`clock.${doh_target}`);

// --------------------------------------------------------------------------------------------
// Tests run inside the test fixture (fixture tests)
//
// If there was an error thrown by the code run by fixtureRun(), it can be detected after
//   the fixtureRun() call by checking if the fixtureLastError global variable is not
//   undefined. If it isn't, then it is set to the Error object (which can be a generic
//   Error or a ContractCheckError).
// --------------------------------------------------------------------------------------------

fixtureRun("metaBoot.js");

fixtureRun("metaStake.js");

fixtureRun("metaBuy.js");

fixtureRun("metaTransfer.js");

fixtureRun("metaDutch.js");

fixtureRun("metaWaitlist.js");

fixtureRun("metaBid.js");

fixtureRun("metaInvite.js");

fixtureRun("metaAuctionLimit.js");

fixtureRun("metaRestrictedLimit.js");

fixtureRun("metaFinal.js");

// --------------------------------------------------------------------------------------------
// Done
// --------------------------------------------------------------------------------------------

fixtureFinish();
