#!/usr/bin/perl

$| = 1;

use strict;
use warnings;

my $driver = "coldstart";
my $dir = "../../tools/reference-contracts";
my $file = "build.sh";
my $build_success = "BUILD_SUCCESS";

# go to driver dir
use FindBin qw($RealBin);
if (chdir($RealBin)) {
    print "$driver: Changed working directory to driver location: $RealBin\n";
} else {
    print "ERROR: $driver: Failed to change working directory to driver directory: $!\n";
    exit 1;
}

# check that the tools/reference-contracts submodule is there
print "$driver: Checking for reference-contracts at $dir\n";
if (! -e "$dir/$file") {
    print "ERROR: $driver: Antelope.io reference-contracts not found in the expected tools directory path.\n";
    exit 1;
}

# go to the tools/reference-contracts directory
print "$driver: Directory found.\n";
if (chdir($dir)) {
    print "$driver: Changed working directory to tools/reference-contracts directory\n";
} else {
    print "ERROR: $driver: Failed to change working directory to tools/reference-contracts directory: $!\n";
}

# skip building if the build directory already exists and it has a magic BUILD_SUCCESS file in it
if (-e "build/$build_success") {
    print "$driver: Antelope.io reference-contracts seems to be already built (build/$build_success marker file found). Skipping (re)build.\n";
    exit 0;
}

# run build
print "$driver: Running reference-contracts build script...\n";
system("./" . "$file");

# Check the exit status of the build script
my $ret = $?;
print "$driver: Contract build script raw exit code (must be zero): $ret\n";
if ($ret == 0) {
    `touch build/$build_success`;
    print "$driver: Reference contracts built successfully\n";
} else {
    my $exit_status = $ret >> 8;
    print "ERROR: $driver: Reference contracts build failed with error code: $exit_status\n";
    `rm -f build/$build_success`;
    exit 1;
}
