#!/usr/bin/perl

my $driver = "coldstart";
my $dir = "../../tools/reference-contracts/";
my $file = "build.sh";

print "$driver: Checking for reference-contracts at $dir\n";

if (-e "$dir$file") {
    print "$driver: Directory found. Running reference contracts build script...\n";
    chdir $dir;
    system("$file");
} else {
    print "$driver: ERROR: Antelope.io reference-contracts not found in the expected tools directory path.\n";
    exit 1;
}

# Check the exit status of the build script
my $ret = $?;
print "$driver: Contract build script raw exit code (must be zero): $ret\n";
if ($ret == 0) {
    print "$driver: Reference contracts built successfully\n";
} else {
    my $exit_status = $ret >> 8;
    print "$driver: ERROR: Reference contracts build failed with error code: $exit_status\n";
    exit 1;
}

