#!/bin/bash

# make sure the current working dir is where this script is
cd "$(dirname "$0")"


if [ -f "./nodeos.pid" ]; then
pid=`cat "./nodeos.pid"`
echo $pid
kill $pid
rm -r "./nodeos.pid"
echo -ne "Stoping nodeos.."
while true; do
[ ! -d "/proc/$pid/fd" ] && break
echo -ne "."
sleep 1
done
echo -ne "\nnodeos stopped.\n"
fi
