#!/usr/bin/perl

# ------------------------------------------
# This just clears the backing driver
# ------------------------------------------

use strict;
use warnings;

my $coldstart_dir = "../coldstart";

use FindBin qw($RealBin);
if (!chdir($RealBin)) {
    print "ERROR: Failed to change working directory: $!\n";
    exit 1;
}

print "Clearing coldstart ...\n";

my $cmd = "$coldstart_dir/clear";
my $o = `$cmd`;
if ($? != 0) {
    print "ERROR: coldstart clear returned an error code.\n";
    print "Output: $o\n";
    exit 1;
}
