#!/bin/bash

cd "$(dirname "$0")"
if ! cd "../../local/doh-hotstart"; then
  echo "doh-hotstart nuke: cannot change directory to local/doh-hotstart; assuming no running doh-hotstart session to nuke"
  exit 0
fi

# just go nuclear
pkill -f nodeos
rm -rf instances
