#!/usr/bin/env node

console.log(`Testing cth javascript support.`);

// Print all command line arguments
process.argv.slice(2).forEach((arg, index) => {
  console.log(`Argument ${index + 1}: ${arg}`);
});

console.log(`Done testing cth javascript support.`);
