#!/usr/bin/env node

// --------------------------------------------------------------------------------------------
// meta-spam
// --------------------------------------------------------------------------------------------
// Test that the meta contract's anti-spam mechanism is working.
// --------------------------------------------------------------------------------------------

Object.assign(global, require('DoHTestFixture'));

fixtureInit("dohplayer1", "hg3", "tc3");

createBasicGame();
createBasicPlayers();
createBasicEconomy();

fixtureRun("metaSpam.js");

fixtureRun("metaSpamFast.js");

fixtureFinish();
